title:            jonwho?
description:      A jekyll theme. Because I scribble.
url:              # Site url, without a slash at the end.
signoff:          Jon Ho
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         Blog
    url:          /
  - name:         About
    url:          /about
  - name:         Projects
    url:          /projects
  - name:         Resume
    url:          http://jonwho.github.io/resume
    external:     true
  - name:         GitHub
    url:          http://github.com/jonwho
    external:     true
  - name:         LinkedIn
    url:          http://linkedin.com/in/jonwho
    external:     true
highlighter:      rouge
permalink:        pretty
markdown:         kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
